# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tictactoe-server

on:
  push:
    paths:
      -Server/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://registry0104.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_e9d42a4b48ff4e1893802ad258d1a9fe }}
          password: ${{ secrets.AzureAppService_ContainerPassword_f76de62a4cba434080b6ef93df2c186b }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry0104.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9d42a4b48ff4e1893802ad258d1a9fe }}/samples/tic-tac-toe:${{ github.sha }}
          file: ./Dockerfile
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tictactoe-server'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a36c5bd2320149e6930012c87cb8cc37 }}
          images: 'registry0104.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9d42a4b48ff4e1893802ad258d1a9fe }}/samples/tic-tac-toe:${{ github.sha }}'
